"""
Centroid-based re-centering for VFX frames.
For each frame: find the weighted centroid of the brightest pixels (the "hot core"),
then re-paste all frames so their centroids align at one consistent point.

Usage:
  python fix_centering.py emp_strike       <- fix one effect
  python fix_centering.py all              <- fix all effects
"""
from PIL import Image
import numpy as np
import os, sys, json, shutil

SRC_DIR  = r"C:\Work\stellar-drift\client\VFX _1\cleaned"
ASSET    = r"C:\Work\stellar-drift\client\assets\vfx"
MANIFEST = os.path.join(ASSET, "vfx_manifest.json")

GRIDS = {
    "EMP Strike skill.png":          ("emp_strike",        4, 4, 16),  # 1536x1024
    "Engine particle.png":           ("engine_particle",   3, 4, 12),  # 1254x1254
    "Hull hit.png":                  ("hull_hit",          4, 3, 12),  # 1536x1024, 3 rows
    "Laser beam1.png":               ("laser_beam1",       4, 3, 12),  # 1536x1024
    "Laser beam2.png":               ("laser_beam2",       4, 2,  8),  # 1536x1024
    "Plasma bolt.png":               ("plasma_bolt",       4, 4, 16),  # 1536x1024, 4 rows
    "plasma burst skill effect.png": ("plasma_burst",      4, 3, 12),  # 1536x1024, 3 rows
    "Repair Pulse skill.png":        ("repair_pulse",      4, 4, 16),  # 1536x1024, 4 rows
    "Targeting reticle.png":         ("targeting_reticle", 2, 3,  6),  # 1024x1536, 2 cols
}

# ── Per-effect strategy ──────────────────────────────────────────────────────
# 'centroid'  : re-align all frames so their bright-core centroid is at
#               one consistent point. Best for symmetric/spot effects.
# 'simple_pad': just pad the raw cell uniformly. Best for effects where
#               the hot core MOVES as part of the animation (explosions, bolts).
STRATEGY = {
    "emp_strike":        "manual",           # manually positioned via frame_editor.html
    "engine_particle":   "manual",           # manually positioned via frame_editor.html
    "hull_hit":          "manual",           # manually positioned via frame_editor.html
    "laser_beam1":       "manual",           # manually positioned via frame_editor.html
    "laser_beam2":       "manual",           # manually positioned via frame_editor.html
    "plasma_bolt":       "manual",           # manually positioned via frame_editor.html
    "plasma_burst":      "manual",           # manually positioned via frame_editor.html
    "repair_pulse":      "manual",           # manually positioned via frame_editor.html
    "targeting_reticle": "manual",           # manually positioned via frame_editor.html
}

BRIGHT_THR = {
    "emp_strike":        210,
    "engine_particle":   220,
    "hull_hit":          180,  # orange fire core
    "laser_beam1":       230,
    "laser_beam2":       200,
    "repair_pulse":      210,
    "targeting_reticle": 180,
}

# Limit centroid search to left fraction of cell width.
# engine_particle: nozzle is always in the left ~40%; the exhaust plume
# grows rightward and drags a full-cell centroid leftward each frame.
CENTROID_X_FRAC = {
    "engine_particle": 0.40,
}

# Edge fade: fade alpha to 0 over this many pixels at each cell border.
# Hides content that bleeds from adjacent cells in the original sheet.
EDGE_FADE = {
    "hull_hit": 40,   # large explosions overflow cell boundaries
}

# fps override per effect
FPS_OVERRIDE = {
    "hull_hit":          12,
    "plasma_bolt":       16,   # 16f @ 16fps = 1.0s
    "plasma_burst":      16,   # 16f @ 16fps = 1.0s
    "repair_pulse":      14,   # 16f @ 14fps = 1.14s
    "targeting_reticle": 8,    # 6f  @  8fps = 0.75s
}

PAD = 0.12   # uniform padding for simple_pad
PAD_C = 0.18  # padding for centroid mode (needs more room for shifted content)

# Manual offsets: (ox, oy) = where to paste the raw cell's top-left in the output canvas.
# Generated by hull_hit_editor.html — paste the dict body here after editing.
MANUAL_OFFSETS = {}
MANUAL_OFFSETS["hull_hit"] = {
    0: (83, 75),
    1: (128, 77),
    2: (157, 76),
    3: (152, 73),
    4: (91, 140),
    5: (121, 137),
    6: (145, 137),
    7: (154, 136),
    8: (92, 164),
    9: (118, 163),
    10: (150, 155),
    11: (153, 155),
}
MANUAL_OFFSETS["laser_beam1"] = {
    0: (112, 101),
    1: (148, 97),
    2: (169, 95),
    3: (137, 93),
    4: (120, 132),
    5: (148, 133),
    6: (110, 110),
    7: (123, 128),
    8: (104, 152),
    9: (146, 152),
    10: (167, 152),
    11: (161, 152),
}
MANUAL_OFFSETS["laser_beam2"] = {
    0: (110, -89),
    1: (149, -85),
    2: (165, -88),
    3: (167, -88),
    4: (104, 107),
    5: (151, 107),
    6: (163, 106),
    7: (165, 106),
}
MANUAL_OFFSETS["emp_strike"] = {
    0: (92, 36),
    1: (132, 34),
    2: (140, 36),
    3: (140, 36),
    4: (92, 37),
    5: (130, 38),
    6: (142, 38),
    7: (137, 35),
    8: (90, 43),
    9: (129, 45),
    10: (137, 45),
    11: (135, 41),
    12: (90, 48),
    13: (128, 48),
    14: (134, 48),
    15: (139, 43),
}
MANUAL_OFFSETS["engine_particle"] = {
    0: (246, 50),
    1: (253, 50),
    2: (259, 50),
    3: (243, 93),
    4: (251, 93),
    5: (259, 94),
    6: (244, 125),
    7: (250, 124),
    8: (256, 125),
    9: (243, 150),
    10: (249, 149),
    11: (254, 151),
}
# Output canvas size for manual strategy (width, height).
MANUAL_CANVAS = {
    "emp_strike":        (640, 420),
    "engine_particle":   (700, 520),
    "hull_hit":          (560, 500),
    "laser_beam1":       (620, 500),
    "laser_beam2":       (620, 660),
    "plasma_bolt":       (640, 420),
    "plasma_burst":      (620, 500),
    "repair_pulse":      (640, 420),
    "targeting_reticle": (720, 720),
}
MANUAL_OFFSETS["plasma_bolt"] = {
    0: (83, 23),
    1: (67, 21),
    2: (58, 21),
    3: (40, 18),
    4: (51, 50),
    5: (50, 51),
    6: (53, 51),
    7: (31, 50),
    8: (49, 62),
    9: (47, 63),
    10: (54, 63),
    11: (38, 63),
    12: (49, 47),
    13: (43, 48),
    14: (49, 49),
    15: (51, 48),
}
MANUAL_OFFSETS["plasma_burst"] = {
    0: (83, 79),
    1: (124, 77),
    2: (149, 81),
    3: (139, 80),
    4: (87, 147),
    5: (117, 147),
    6: (136, 146),
    7: (139, 146),
    8: (126, 68),
    9: (128, 73),
    10: (129, 98),
    11: (128, 87),
}
MANUAL_OFFSETS["repair_pulse"] = {
    0: (96, 22),
    1: (132, 23),
    2: (142, 25),
    3: (143, 24),
    4: (99, 31),
    5: (124, 33),
    6: (136, 33),
    7: (137, 27),
    8: (97, 48),
    9: (121, 45),
    10: (134, 45),
    11: (130, 41),
    12: (101, 58),
    13: (118, 61),
    14: (130, 58),
    15: (135, 56),
}
MANUAL_OFFSETS["targeting_reticle"] = {
    0: (98, 40),
    1: (104, 38),
    2: (104, 103),
    3: (103, 98),
    4: (104, 96),
    5: (102, 96),
}


def apply_edge_fade(cell, fade_px):
    """Linearly fade alpha to 0 over `fade_px` pixels at all four edges."""
    h, w = cell.shape[:2]
    f = min(fade_px, h // 3, w // 3)
    ramp = np.linspace(0.0, 1.0, f)
    # Top and bottom
    for i in range(f):
        cell[i,      :, 3] = (cell[i,      :, 3] * ramp[i]).astype(np.uint8)
        cell[h-1-i,  :, 3] = (cell[h-1-i,  :, 3] * ramp[i]).astype(np.uint8)
    # Left and right
    for i in range(f):
        cell[:,      i, 3] = (cell[:,      i, 3] * ramp[i]).astype(np.uint8)
        cell[:, w-1-i, 3] = (cell[:, w-1-i, 3] * ramp[i]).astype(np.uint8)
    return cell


def cut_raw_cells(path, nc, nr, nframes, edge_fade=0):
    """Return raw RGBA crops (numpy arrays) at original grid boundaries."""
    img = Image.open(path).convert("RGBA")
    arr = np.array(img)
    W, H = img.size
    xs = [int(round(i * W / nc)) for i in range(nc + 1)]
    ys = [int(round(i * H / nr)) for i in range(nr + 1)]
    cells = []
    for idx in range(nframes):
        r, c = divmod(idx, nc)
        cell = arr[ys[r]:ys[r+1], xs[c]:xs[c+1], :].copy()
        if edge_fade > 0:
            cell = apply_edge_fade(cell, edge_fade)
        cells.append(cell)
    return cells


def find_centroid(cell_arr, thr, x_frac=1.0):
    """
    Weighted centroid of pixels brighter than `thr` (max of RGB channels).
    x_frac: only consider pixels in the left (x_frac * width) columns.
             Use < 1.0 for effects where the hot core is always on one side
             (e.g. engine_particle nozzle on the left, exhaust grows right).
    Falls back to progressively lower thresholds if no pixels qualify.
    Returns (cx, cy) in pixel coords of the cell.
    """
    h, w2 = cell_arr.shape[:2]
    brightness = cell_arr[:, :, :3].max(axis=-1).astype(float)
    if x_frac < 1.0:
        x_limit = int(w2 * x_frac)
        brightness[:, x_limit:] = 0  # mask out right portion
    for t in [thr, thr - 30, thr - 60, int(brightness.max() * 0.5), 0]:
        mask = brightness > t
        if mask.sum() > 10:
            ys, xs = np.where(mask)
            w = brightness[mask]
            return float(np.average(xs, weights=w)), float(np.average(ys, weights=w))
    return float(w2 * x_frac / 2), float(h / 2)


def repack(cells, centroids, pad=PAD):
    """
    Re-paste all cells so their centroids line up at a common point.
    Returns (list of PIL Images, output_fw, output_fh, anchor_x, anchor_y).
    """
    cx_arr = np.array([c[0] for c in centroids])
    cy_arr = np.array([c[1] for c in centroids])

    # Stable anchor = median centroid (robust against outliers like frame_00)
    ax = float(np.median(cx_arr))
    ay = float(np.median(cy_arr))

    cell_h, cell_w = cells[0].shape[:2]

    # Compute required canvas size so no content is clipped after any shift
    max_left  = ax + max(0, max(ax - cx for cx, _ in centroids))
    max_right = (cell_w - ax) + max(0, max(cx - ax for cx, _ in centroids))
    max_top   = ay + max(0, max(ay - cy for _, cy in centroids))
    max_bot   = (cell_h - ay) + max(0, max(cy - ay for _, cy in centroids))

    # Content size = bounding box that fits every shifted cell
    content_w = max_left + max_right
    content_h = max_top  + max_bot

    # Add padding, round to even
    fw = int(np.ceil(content_w * (1 + 2 * pad) / 2) * 2)
    fh = int(np.ceil(content_h * (1 + 2 * pad) / 2) * 2)

    # Canvas anchor = where we want the centroid to land
    out_ax = fw // 2
    out_ay = fh // 2

    images = []
    for cell, (cx, cy) in zip(cells, centroids):
        canvas = Image.new("RGBA", (fw, fh), (0, 0, 0, 0))
        ox = int(round(out_ax - cx))
        oy = int(round(out_ay - cy))
        canvas.paste(Image.fromarray(cell), (ox, oy))
        images.append(canvas)

    return images, fw, fh, out_ax, out_ay


def pack_sheet(frames, fw, fh):
    n = len(frames)
    sheet = Image.new("RGBA", (fw * n, fh), (0, 0, 0, 0))
    for i, img in enumerate(frames):
        sheet.paste(img, (i * fw, 0))
    return sheet


def simple_pad_frames(cells, pad=PAD):
    """Uniform padding only — no content-based shift."""
    import math
    cell_h, cell_w = cells[0].shape[:2]
    fw = int(math.ceil(cell_w * (1 + 2 * pad) / 2) * 2)
    fh = int(math.ceil(cell_h * (1 + 2 * pad) / 2) * 2)
    ox = (fw - cell_w) // 2
    oy = (fh - cell_h) // 2
    images = []
    for cell in cells:
        canvas = Image.new("RGBA", (fw, fh), (0, 0, 0, 0))
        canvas.paste(Image.fromarray(cell), (ox, oy))
        images.append(canvas)
    return images, fw, fh


def process_effect(folder_name):
    src_entry = None
    for fname, (fold, nc, nr, nframes) in GRIDS.items():
        if fold == folder_name:
            src_entry = (fname, fold, nc, nr, nframes)
            break
    if not src_entry:
        print(f"  ERROR: unknown effect '{folder_name}'"); return

    fname, folder, nc, nr, nframes = src_entry
    src_path = os.path.join(SRC_DIR, fname)
    strategy = STRATEGY.get(folder, "simple_pad")

    print(f"\n[ {folder} ]  strategy={strategy}  grid={nc}x{nr}  frames={nframes}")

    # For manual strategy: load pre-edited frames from {folder}_raw/ if they exist,
    # otherwise cut from the source sprite sheet as usual.
    raw_dir = os.path.join(ASSET, f"{folder}_raw")
    raw_frames_exist = (strategy == "manual" and
                        os.path.isdir(raw_dir) and
                        os.path.exists(os.path.join(raw_dir, "frame_00.png")))

    if raw_frames_exist:
        cells = []
        for i in range(nframes):
            p = os.path.join(raw_dir, f"frame_{i:02d}.png")
            cells.append(np.array(Image.open(p).convert("RGBA")))
        print(f"  loaded {nframes} pre-edited frames from {folder}_raw/")
    else:
        cells = cut_raw_cells(src_path, nc, nr, nframes, edge_fade=EDGE_FADE.get(folder, 0))

    if strategy == "manual":
        mo = MANUAL_OFFSETS.get(folder, {})
        fw, fh = MANUAL_CANVAS.get(folder, (cells[0].shape[1] + 80, cells[0].shape[0] + 80))
        if not mo:
            print(f"  WARNING: no manual offsets — use frame_editor.html to set them")
            default_ox = (fw - cells[0].shape[1]) // 2
            default_oy = (fh - cells[0].shape[0]) // 2
            mo = {i: (default_ox, default_oy) for i in range(len(cells))}
        images = []
        for i, cell in enumerate(cells):
            ox, oy = mo.get(i, ((fw - cell.shape[1]) // 2, (fh - cell.shape[0]) // 2))
            canvas = Image.new("RGBA", (fw, fh), (0, 0, 0, 0))
            canvas.paste(Image.fromarray(cell), (ox, oy))
            images.append(canvas)
        print(f"  manual  frames={len(images)}  output frame: {fw}x{fh}")
    elif strategy == "simple_pad":
        images, fw, fh = simple_pad_frames(cells, pad=PAD)
        print(f"  output frame: {fw}x{fh}  (simple pad {PAD*100:.0f}%)")
    elif strategy == "centroid_y":
        # Correct only vertical drift; keep each frame's X at geometric cell centre.
        # Prevents left-right flicker caused by horizontally asymmetric explosions.
        thr = BRIGHT_THR.get(folder, 200)
        xf  = CENTROID_X_FRAC.get(folder, 1.0)
        raw_centroids = [find_centroid(c, thr, x_frac=xf) for c in cells]
        cw0 = cells[0].shape[1]
        # Replace cx with the fixed geometric centre of the cell
        centroids = [(cw0 / 2.0, cy) for (_, cy) in raw_centroids]
        cys = [c[1] for c in centroids]
        print(f"  centroid_y  Y range={max(cys)-min(cys):.1f}px  thr={thr}  (X fixed at cell centre)")
        images, fw, fh, ax, ay = repack(cells, centroids, pad=PAD_C)
        print(f"  output frame: {fw}x{fh}  anchor=({ax},{ay})")
    elif strategy == "centroid_detrend":
        # Remove systematic grid biases before re-centering.
        # Column position creates a consistent cx offset (col0 bright core is
        # always further right than col3). Row position creates a consistent cy
        # offset (row0 fire core is lower than row2 because fire rises).
        # Detrending subtracts these per-column/per-row means so repack only
        # compensates for genuine per-frame variation (~10-15px), not grid artefacts.
        thr = BRIGHT_THR.get(folder, 200)
        xf  = CENTROID_X_FRAC.get(folder, 1.0)
        raw = [find_centroid(c, thr, x_frac=xf) for c in cells]

        # Per-column mean cx, per-row mean cy
        col_sums = {}; col_n = {}
        row_sums = {}; row_n = {}
        for idx, (cx, cy) in enumerate(raw):
            r, c = divmod(idx, nc)
            col_sums[c] = col_sums.get(c, 0.0) + cx
            col_n[c]    = col_n.get(c, 0) + 1
            row_sums[r] = row_sums.get(r, 0.0) + cy
            row_n[r]    = row_n.get(r, 0) + 1
        col_mean = {c: col_sums[c] / col_n[c] for c in col_sums}
        row_mean = {r: row_sums[r] / row_n[r] for r in row_sums}
        gcx = sum(cx for cx, _ in raw) / len(raw)
        gcy = sum(cy for _, cy in raw) / len(raw)

        centroids = []
        for idx, (cx, cy) in enumerate(raw):
            r, c = divmod(idx, nc)
            centroids.append((cx - (col_mean[c] - gcx),
                               cy - (row_mean[r] - gcy)))

        cxs = [c[0] for c in centroids]
        cys = [c[1] for c in centroids]
        print(f"  centroid_detrend  cx range={max(cxs)-min(cxs):.1f}px  cy range={max(cys)-min(cys):.1f}px  thr={thr}")
        print(f"  col cx means: { {c: f'{v:.0f}' for c,v in col_mean.items()} }")
        print(f"  row cy means: { {r: f'{v:.0f}' for r,v in row_mean.items()} }")
        images, fw, fh, ax, ay = repack(cells, centroids, pad=PAD_C)
        print(f"  output frame: {fw}x{fh}  anchor=({ax},{ay})")
    else:
        thr = BRIGHT_THR.get(folder, 200)
        xf  = CENTROID_X_FRAC.get(folder, 1.0)
        centroids = [find_centroid(c, thr, x_frac=xf) for c in cells]
        cxs = [c[0] for c in centroids]
        cys = [c[1] for c in centroids]
        print(f"  centroid X range={max(cxs)-min(cxs):.1f}px  Y range={max(cys)-min(cys):.1f}px  thr={thr}  xfrac={xf}")
        images, fw, fh, ax, ay = repack(cells, centroids, pad=PAD_C)
        print(f"  output frame: {fw}x{fh}  anchor=({ax},{ay})")

    # Save individual frames
    frame_dir = os.path.join(ASSET, folder)
    os.makedirs(frame_dir, exist_ok=True)
    for i, img in enumerate(images):
        img.save(os.path.join(frame_dir, f"frame_{i:02d}.png"))

    # Save sprite sheet
    sheet = pack_sheet(images, fw, fh)
    sheet_path = os.path.join(ASSET, f"{folder}_sheet.png")
    sheet.save(sheet_path)
    print(f"  Sheet: {folder}_sheet.png  ({fw*nframes}x{fh})")

    # Update manifest
    with open(MANIFEST, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    manifest[folder]["frameWidth"]  = fw
    manifest[folder]["frameHeight"] = fh
    manifest[folder]["frameCount"]  = nframes
    if folder in FPS_OVERRIDE:
        manifest[folder]["fps"] = FPS_OVERRIDE[folder]
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"  Manifest updated.")


# ── Entry point ──────────────────────────────────────────────────────────────
targets = sys.argv[1:] if len(sys.argv) > 1 else ["emp_strike"]
if targets == ["all"]:
    targets = [fold for _, (fold, *_) in GRIDS.items()]

for t in targets:
    process_effect(t)

print("\nDone!")
